[rule]
description = standard text checks followed by US SSN syntax

# Separate lines mean OR. A + means that both components must be present.
automatic_field_types = text
automatic_field_name_patterns =
    ssn
    social + security

[composite_rule]
rules =
    standard_text_composite
    ssn_base
