[rule]
# Short text displayed by bin/dq --list_rules.
description = standard text checks followed by the part number example format

# Demonstrates automatic matching with two required field-name components.
automatic_field_types = text
automatic_field_name_patterns =
    part + number

[composite_rule]
# Apply these rules in order.
# Composite rules may include other composites.
# Composite rules are recursivly expanded into their base rules.
# DQ runs the low level rules in order until it finds a failure or completes all without error
rules =
    standard_text_composite
    part_number_example_base
